export {
  ApiRequestError,
  AUTH_ERROR_PARAM,
  DATABASE_CHECK,
  WEEKDAYS,
  changePassword,
  clearDuration,
  createAppointmentType,
  createMyBlock,
  createResource,
  createResourceType,
  createSpecialty,
  createStaffAccount,
  deactivateStaffAccount,
  defineException,
  defineWorkingHours,
  disableStaffAccount,
  enableStaffAccount,
  findStaffAccountByEmail,
  getHealth,
  getAvailability,
  getBookingOptions,
  bookAppointment,
  bookAppointmentForPatient,
  cancelAppointment,
  calendarConnectUrl,
  checkCalendarConnection,
  disconnectCalendar,
  getCalendarConnection,
  grantConsent,
  getMyProfile,
  getProfessional,
  getScheduleDay,
  getSession,
  googleSignInUrl,
  grantSpecialty,
  listAppointmentTypes,
  listMyAppointments,
  listMyBlocks,
  listProfessionals,
  listResourceTypes,
  listResources,
  listSpecialties,
  listStaffAccounts,
  onSessionEnded,
  renameProfessional,
  renameSpecialty,
  retireException,
  retireWorkingHours,
  revokeConsent,
  resolvePatientByEmail,
  revokeSpecialty,
  setCatalogEntityActive,
  setMyBlockActive,
  setDuration,
  signIn,
  signOut,
  rescheduleAppointment,
  updateAppointmentType,
  updateMyBlock,
  updateMyProfile,
  updateResource,
  updateResourceType,
  type ApiError,
  type AppointmentTypeResponse,
  type AppointmentResponse,
  type MyAppointment,
  type MyAppointmentsResponse,
  type AvailabilityResponse,
  type AvailabilitySlotResponse,
  type BookableAppointmentType,
  type BookableProfessional,
  type BookableSpecialty,
  type BookingOptionsResponse,
  type CalendarConnectionResponse,
  type CalendarDisconnectResponse,
  type CatalogCollection,
  type ConfiguredDuration,
  type ConsentResponse,
  type HeldSpecialty,
  type HealthResponse,
  type PatientProfileResponse,
  type ProfessionalDetail,
  type ProfessionalListEntry,
  type ResolvedPatient,
  type ResourceResponse,
  type ResourceTypeResponse,
  type RoleName,
  type SessionResponse,
  type ScheduleDayResponse,
  type ScheduledAppointment,
  type ScheduledBlock,
  type SpecialtyResponse,
  type SaveTimeBlockInput,
  type StaffAccountResponse,
  type StaffAppointmentResponse,
  type TimeBlockListResponse,
  type TimeBlockResponse,
  type Weekday,
  type WorkingHoursOverride,
  type WorkingHoursSegment,
} from './api/client';

export {
  DEFAULT_LANGUAGE,
  SUPPORTED_LANGUAGES,
  resources,
  type SupportedLanguage,
} from './i18n/index';

export { createI18n } from './i18n/setup';

export {
  addDays,
  clinicDate,
  clinicDayLabel,
  clinicOffset,
  clinicShortDate,
  clinicTime,
  clinicToday,
  minutesBetween,
} from './time/clinicClock';

export {
  RequireAuth,
  SESSION_QUERY_KEY,
  SessionExpiryWatcher,
  useApiCodeMessage,
  useApiErrorMessage,
  useSession,
  useSignOut,
} from './auth/session';

export { HealthPanel } from './ui/HealthPanel';
export { LanguageSwitch } from './ui/LanguageSwitch';

export { cn } from './ui/cn';
export { Button, buttonVariants, type ButtonProps } from './ui/primitives/Button';
export {
  Field,
  Input,
  Label,
  RadioGroup,
  Select,
  type RadioGroupProps,
  type RadioOption,
} from './ui/primitives/Field';
export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogTrigger,
  type DialogContentProps,
} from './ui/primitives/Dialog';
export {
  Alert,
  Badge,
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
  Table,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
  type AlertProps,
  type BadgeProps,
} from './ui/primitives/Surfaces';
