export {
  ApiRequestError,
  AUTH_ERROR_PARAM,
  DATABASE_CHECK,
  WEEKDAYS,
  changePassword,
  clearDuration,
  createAppointmentType,
  createMyBlock,
  createResource,
  createResourceType,
  createSpecialty,
  createStaffAccount,
  defineException,
  defineWorkingHours,
  disableStaffAccount,
  getHealth,
  getAvailability,
  getMyProfile,
  getProfessional,
  getSession,
  googleSignInUrl,
  grantSpecialty,
  listAppointmentTypes,
  listMyBlocks,
  listProfessionals,
  listResourceTypes,
  listResources,
  listSpecialties,
  listStaffAccounts,
  onSessionEnded,
  renameSpecialty,
  retireException,
  retireWorkingHours,
  revokeConsent,
  revokeSpecialty,
  setCatalogEntityActive,
  setMyBlockActive,
  setDuration,
  signIn,
  signOut,
  updateAppointmentType,
  updateMyBlock,
  updateMyProfile,
  updateResource,
  updateResourceType,
  type ApiError,
  type AppointmentTypeResponse,
  type AvailabilityResponse,
  type AvailabilitySlotResponse,
  type CatalogCollection,
  type ConfiguredDuration,
  type ConsentResponse,
  type HeldSpecialty,
  type HealthResponse,
  type PatientProfileResponse,
  type ProfessionalDetail,
  type ProfessionalListEntry,
  type ResourceResponse,
  type ResourceTypeResponse,
  type RoleName,
  type SessionResponse,
  type SpecialtyResponse,
  type SaveTimeBlockInput,
  type StaffAccountResponse,
  type TimeBlockListResponse,
  type TimeBlockResponse,
  type Weekday,
  type WorkingHoursOverride,
  type WorkingHoursSegment,
} from './api/client';

export {
  DEFAULT_LANGUAGE,
  SUPPORTED_LANGUAGES,
  resources,
  type SupportedLanguage,
} from './i18n/index';

export { createI18n } from './i18n/setup';

export {
  RequireAuth,
  SESSION_QUERY_KEY,
  SessionExpiryWatcher,
  useApiCodeMessage,
  useApiErrorMessage,
  useSession,
  useSignOut,
} from './auth/session';

export { HealthPanel } from './ui/HealthPanel';
export { LanguageSwitch } from './ui/LanguageSwitch';

export { cn } from './ui/cn';
export { Button, buttonVariants, type ButtonProps } from './ui/primitives/Button';
export { Field, Input, Label, Select } from './ui/primitives/Field';
export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogTrigger,
  type DialogContentProps,
} from './ui/primitives/Dialog';
export {
  Alert,
  Badge,
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
  Table,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
  type AlertProps,
  type BadgeProps,
} from './ui/primitives/Surfaces';
